### ISSUE TITLE
Put more things in AutoProcProgramAttachment

### ISSUE THREAD

**Issue by rjgildea** [DiamondLightSource/fast_dp#17]
Currently only fast_dp.log and fast_dp.mtz are included as AutoProcProgramAttachment.

Suggestion to add:
fast_dp_unmerged.mtz
aimless.log
autoindex.log
pointless.log
xtriage.log

Any others?

https://jira.diamond.ac.uk/browse/MXSW-953

**Comment by Anthchirp** [comment]
resolved by zocalo wrapper
