### ISSUE TITLE
Generate scaled_unmerged.mtz

### ISSUE THREAD

**Issue by rjgildea** [DiamondLightSource/fast_dp#2]
Please could fast_dp generate a scaled_unmerged.mtz? Just needs to add the following input to aimless:
`output unmerged
`

**Comment by graeme-winter** [comment]
Will do

Though you can use sorted Metz equivalently

**Comment by rjgildea** [comment]
Is the sorted.mtz already scaled?

**Comment by graeme-winter** [comment]
Yes: it is only merged in aimless, all of the scaling was already performed
with the XDS CORRECT step
