### ISSUE TITLE
Replace image header reading code with dxtbx from DIALS

### ISSUE THREAD

**Issue by graeme-winter** [DiamondLightSource/fast_dp#21]
Since this is a dependency anyway it would seem sane to make it the only way to read image headers. That way we would get for no cost proper support for full imgCIF files etc. See also SCI-7774 in DLS JIRA.

**Comment by graeme-winter** [comment]
- [ ] update metadata with a goniometer vector
- [ ] update metadata with detector fast and slow vectors
- [ ] update metadata with a beam vector

These should all follow IUCr / imgCIF conventions i.e. correspond to that which you get from dxtbx

**Comment by graeme-winter** [comment]
Then:
- [ ] update templates to use these vectors
- [ ] replace image header reading code with dxtbx.load for single frame cases

**Comment by graeme-winter** [comment]
Making sure that this continues to work for P12M on I23 at Diamond will be interesting - will require (probably) pulling all the XDS panel writing stuff out and pushing that back in explicitly via the metadata.

**Comment by graeme-winter** [comment]
For 12M will need to be able to add in e.g.

```
!
! SEGMENT 13
!
SEGMENT=  989 1475 425 619
DIRECTION_OF_SEGMENT_X-AXIS=  1.00000 -0.00034 -0.00060
DIRECTION_OF_SEGMENT_Y-AXIS=  0.00065 0.14764 0.98904
SEGMENT_ORGX=  1230.78
SEGMENT_ORGY=  521.60
SEGMENT_DISTANCE=  250.08
```

et seq. => will probably be hard to do this templated; almost certainly better to simply calculate the templates ab initio.

**Comment by graeme-winter** [comment]
Will _start_ by developing against Eiger and I23 P12M data => the easy stuff should just work.

**Comment by rjgildea** [comment]
All the tools should be already there to output dxtbx objects as XDS.INP and XPARM.XDS files, including support for I23 12M multi-panel detectors:

https://github.com/cctbx/cctbx_project/blob/master/dxtbx/serialize/xds.py#L153

Code used by dials.export format=xds:

https://github.com/dials/dials/blob/master/util/xds.py#L47

**Comment by graeme-winter** [comment]
Yup, aware of this but looking to have something which fits in more idiomatically to the way fast dp works. Obviously it’ll be repurposing the existing code...

**Comment by graeme-winter** [comment]
Assert: geometry information only needed in first XDS.INP - subsequent ones this comes from (G)XPARM.XDS. This statement turns out to be false - you need to include it each time despite the information being stored in XPARM. Otherwise you get:

```

  !!! ERROR !!! INCORRECT DETECTOR SPECIFICATION
```

**Comment by graeme-winter** [comment]
@rjgildea FWIW I am coming around to your way of thinking but it will involve adding some code to tune the XDS.INP for the step in question - I will also need to work out precisely what we want to have in there i.e. where to the output files differ from what we have right now. 

Will also need to pull some of the writer code calculations out to another place and be able to pass these in as overloads i.e. SPOT_RANGE= etc.

**Comment by graeme-winter** [comment]
Would love to use https://github.com/cctbx/cctbx_project/blob/e6066b6063bc30a1246ee4b908738c8f4afbc259/dxtbx/serialize/xds.py#L269 but send output to a _file_

**Comment by graeme-winter** [comment]
https://github.com/cctbx/cctbx_project/commit/c92bbaa89c560c136645a1d86fca8dc29e5b2b70

Ugly!

**Comment by graeme-winter** [comment]
```
Grey-Area:fast_dp graeme$ git push -u origin fast-dp-21
Total 0 (delta 0), reused 0 (delta 0)
remote: 
remote: Create a pull request for 'fast-dp-21' on GitHub by visiting:
remote:      https://github.com/DiamondLightSource/fast_dp/pull/new/fast-dp-21
remote: 
To github.com:/DiamondLightSource/fast_dp
 * [new branch]      fast-dp-21 -> fast-dp-21
Branch 'fast-dp-21' set up to track remote branch 'fast-dp-21' from 'origin'.
```

make a branch to work on this for the moment - want to move all the metadata wrangling to use XDS parameters rather than the existing hodge-podge. Will involve a lot of changes.
