### ISSUE TITLE
fast_dp-report.html rather corpulent

### ISSUE THREAD

**Issue by Anthchirp** [DiamondLightSource/fast_dp#30]
eg ```/dls/i03/data/2018/nt18231-9/processed/tmp/2018-11-15/07-35-33-8f6f713d/INS2_29_2_1_/fast_dp/fast_dp-report.html``` is 12.6 MB.
```.json``` is another 12 MB

I suspect there are a few digits that can be shaved off

**Comment by rjgildea** [comment]
fast_dp-report.html uses xia2.report which also includes the recently-added probability plots that contain several plots that have a point for *every* reflection. See also https://github.com/dials/dials/issues/648

**Comment by Anthchirp** [comment]
Duplicate then. Thanks
