### ISSUE TITLE
HTML log

### ISSUE THREAD

**Issue by graeme-winter** [DiamondLightSource/fast_dp#6]
see html logs for xia2; fast_ep for inspiration... would be very useful to replace current very minimal text version...

**Comment by graeme-winter** [comment]
Short cut could need a little work:

```
>>> xia2.report xds_sorted.mtz 
Traceback (most recent call last):
  File "/Users/graeme/svn/cctbx/build/../modules/xia2/command_line/report.py", line 935, in <module>
    run(sys.argv[1:])
  File "/Users/graeme/svn/cctbx/build/../modules/xia2/command_line/report.py", line 873, in run
    json_data.update(report.scale_rmerge_vs_batch_plot())
  File "/Users/graeme/svn/cctbx/build/../modules/xia2/command_line/report.py", line 425, in scale_rmerge_vs_batch_plot
    sc_vs_b = scales_vs_batch(self.scales, new_batches)
  File "/Users/graeme/svn/cctbx/modules/xia2/Modules/Analysis/__init__.py", line 58, in scales_vs_batch
    assert scales.size() == batches.size()
AttributeError: 'NoneType' object has no attribute 'size'
```

i.e. is not encoded in there - could replace this with a default of [1] for this purpose...

**Comment by rjgildea** [comment]
Can you add:
`output scaled unmerged`
when you run aimless inside fast_dp? This would make it consistent with xia2 and would probably be useful for other things as well.

**Comment by graeme-winter** [comment]
Will do

**Comment by rjgildea** [comment]
We will also need the scaled_unmerged.mtz from fast_dp to generate the merging-statistics.json to put into ISPyB

**Comment by graeme-winter** [comment]
following commit closing #2 testing xia2.report now; seems to work :)

**Comment by rjgildea** [comment]
`xia2.report scaled_unmerged.mtz title="fast_dp report"`

**Comment by graeme-winter** [comment]
```
xia2.report prefix=fast_dp title="fast_dp" fast_dp_unmerged.mtz log_include=fast_dp.log
```

hits the spot #todo add this to the launcher script #todo register the file in the database
